### PR TITLE
Add .editorconfig configuration and .idea to gitignore

### PR DESCRIPTION
**Pull request by BernardoSilva**

### CODE REVIEW

**Comment by VLMH** [comment]
Thanks and sorry for not slow response
Will clear all PRs next week including this one

**Comment by BernardoSilva** [comment]
:+1:  Cool. awesome news.
 Would be awesome if you could review/merge this one: https://github.com/onesky/api-library-php5/pull/19 which contains all existing PR to this library.

**Comment by VLMH** [comment]
Cool! Will review and merge #19 early next week :+1:

**Comment by VLMH** [comment]
Done at #19

**Pull request closed without merging**
