### PR TITLE
Supporting multilingual translations export.

### PR DESCRIPTION
**Pull request by valorin**
Added the `multilingual` translations export option.

Should complete https://github.com/onesky/api-library-php5/issues/26

### CODE REVIEW

**Comment by VLMH** [comment]
Thank you!
Will give it a test and merge.

**Comment by Jurre88** [comment]
@VLMH Can this PR be merged?

**Comment by tomcoonen** [comment]
@VLMH please merge!

**Comment by VLMH** [comment]
first merge and add test next

**Pull request merged**
