### PR TITLE
Some basic improvement

### PR DESCRIPTION
**Pull request by BunnyHolder**

### CODE REVIEW

**Comment by VLMH** [comment]
Will merge after review. Thanks!

**Comment by BernardoSilva** [comment]
:+1: Looks good.
Can you merge this?

**Comment by BernardoSilva** [comment]
@VLMH Created issue https://github.com/onesky/api-library-php5/issues/16 to match improvements in this Pull Request. 

Thanks to @BunnyHolder for those updates.

**Comment by VLMH** [comment]
Done at #19

**Pull request closed without merging**
